#!/usr/bin/bash

config=$HOME/.config/hypr
scripts=$config/scripts

# Fix potential slow startup
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_CURRENT_DESKTOP=sway

# Create dummy service to avoid kded6 from breaking the tray
printf "[D-BUS Service]\nName=org.kde.kded6\nExec=/bin/false" > $HOME/.local/share/dbus-1/services/org.kde.kded6.service

# GNOME like OSD for brightness and volume
swayosd-server &

# Idle daemon
hypridle &

# Wallpaper and Window switcher daemon
$HOME/.config/eww/scripts/daemon &

# Dynamic Monitor management
shikane &

# Sway Notification Center
swaync &

# Systray compatibility for X apps (Wine)
xembedsniproxy &

$scripts/waybar &
# $scripts/restart-eww &

# Focus on window activation
$HOME/.config/sway/scripts/focus_on_urgent &

## Gnome authentication/keyring
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# gnome-keyring-daemon --start --components=pkcs11,secrets,ssh &

# Audio systray icon
pasystray --notify=none &

# Touchpad gestures
fusuma &

# NetworkManager applet
nm-applet &

# Applauncher
albert &

# Enable auto/smart tiling
autotiling-rs &

# Dolphin file associations fix
kbuildsycoca6

# Fix applications such a GParted (X11 root apps under wayland)
xhost +SI:localuser:root

# Lyrics server
lrcsnc &
