#!/bin/bash
# Move a window to the the next or previous workspace on the current monitor.

CURRENT_MONITOR=$(swaymsg -t get_outputs | jq -r 'map(select(.focused))[0].name')

WORKSPACES=(`swaymsg -t get_workspaces | jq -r --arg output "$CURRENT_MONITOR" '[ .[] | select(.output==$output)] | sort_by(.num) | .[] | .num'`)

FOCUSED_WORKSPACE=$(swaymsg -t get_workspaces | jq -r --arg output "$CURRENT_MONITOR" '[ .[] | select(.output==$output and .focused?)] | sort_by(.num) | .[] | .num')

CONID=$(swaymsg -t get_tree | jq '.. | select(.type?) | select(.focused==true) | .id')

TARGET_INDEX=0

FOCUSED_WORKSPACE_INDEX=0
for i in "${!WORKSPACES[@]}"; do
    workspace=${WORKSPACES[$i]}
    if [[ $workspace == $FOCUSED_WORKSPACE ]]; then
        break
    fi
    FOCUSED_WORKSPACE_INDEX=$(($FOCUSED_WORKSPACE_INDEX + 1))
done

if [[ $1 == 'next' ]]; then
    TARGET_INDEX=$(($FOCUSED_WORKSPACE_INDEX + 1))
fi
if [[ $1 == 'prev' ]]; then
    TARGET_INDEX=$(($FOCUSED_WORKSPACE_INDEX - 1))
fi

TARGET_WORKSPACE=${WORKSPACES[$TARGET_INDEX]}

if [[ -z $TARGET_WORKSPACE ]]; then
    # Next workspace doesn't exist create a new one and move the window to it.
    TARGET_WORKSPACE=$($HOME/.config/sway/scripts/workspace_new)
    swaymsg "[con_id=$CONID] focus; floating disable; move window to workspace $TARGET_WORKSPACE"
    swaymsg "workspace $TARGET_WORKSPACE"
else
    swaymsg "[con_id=$CONID] focus; floating disable; move window to workspace $TARGET_WORKSPACE; workspace $TARGET_WORKSPACE"
fi
