#!/usr/bin/sh

windows=`eww --no-daemonize get windows | jq length`
if [[ $windows -eq 0 ]]; then
    echo "No open windows"
    exit
fi

open_state=`eww --no-daemonize active-windows | grep hyprmsn`

if [[ ! -z $open_state ]]; then
    echo "Already open"
    return
fi

eww --no-daemonize open-many hyprmsn hyprmsn-closer --arg monitor=$(swaymsg -t get_outputs | jq -r '.[] | select(.focused == true).name')
