#!/bin/bash
# Move to workspace at offset x on the currently focused monitor.

CURRENT_MONITOR=$(swaymsg -t get_outputs | jq -r 'map(select(.focused))[0].name')

WORKSPACES=(`swaymsg -t get_workspaces | jq -r --arg output "$CURRENT_MONITOR" '[ .[] | select(.output==$output)] | sort_by(.num) | .[] | .num'`)

TARGET_INDEX=$(($1 - 1))

TARGET_WORKSPACE=${WORKSPACES[$TARGET_INDEX]}

swaymsg workspace $TARGET_WORKSPACE
