#!/bin/bash
# Move to workspace at offset x on the currently focused monitor.

CURRENT_MONITOR=`hyprctl -j activeworkspace | jq -r '"\(.monitor)"'`

WORKSPACES=(`hyprctl -j workspaces | jq -r ".[] | select(.monitor | contains(\"$CURRENT_MONITOR\")) | \"\(.id)\"" | sort`)

TARGET_INDEX=$(($1 - 1))

TARGET_WORKSPACE=${WORKSPACES[$TARGET_INDEX]}

hyprctl dispatch workspace $TARGET_WORKSPACE
