swipe:
  3:
    left:
      sendkey: "LEFTALT+RIGHT" # history back
    right:
      sendkey: "LEFTALT+LEFT" # history forward
    up:
      update:
        sendkey: VOLUMEUP
    down:
      update:
        sendkey: VOLUMEDOWN