#!/bin/bash

if hyprctl activeworkspace -j &>/dev/null; then
    hyprland_running=1
fi

if echo $SWAYSOCK &>/dev/null; then
    sway_running=1
fi

kill_all() {
    JOBS=$(jobs -p)
    echo $JOBS
    pkill -9 $JOBS
    kill -9 $JOBS
    echo $JOBS | xargs -I{} kill -- -{}
}

trap 'kill_all; exit' INT

run_daemon() {
    echo "EWW: Starting daemon"
    eww daemon --no-daemonize &

    if [ $sway_running ]; then
        echo "Running on Sway..."

        $HOME/.config/eww/scripts/daemon_sway &
        $HOME/.config/eww/scripts/sway outputs &
        $HOME/.config/eww/scripts/sway monitor &
    elif [ $hyprland_running ]; then
        echo "Running on Hyprland..."

        $HOME/.config/eww/scripts/daemon_hyprland &
        $HOME/.config/eww/scripts/hyprland outputs &
        $HOME/.config/eww/scripts/hyprland monitor &
    fi
}

run_daemon

sleep 1

while true; do
    eww_running=$(eww state 2> /dev/null)
    if [ ! $? -eq 0 ]; then
        echo "EWW: Detected runtime issue, restarting"
        kill_all
        run_daemon
    fi
    sleep 1
done