#!/usr/bin/env bash

window_title() {
    echo `hyprctl activewindow -j | jq --raw-output .title`
}

workspaces() {
    hyprctl workspaces -j | jq 'map({id: .id | tostring, windows: .windows})' | tr -d '\n'
}

if [[ $1 == 'workspaces' ]]; then 
    echo "{ \"workspaces\": $(workspaces), \"active\": 1, \"active_empty\": true }"
    socat -u UNIX-CONNECT:/run/user/1000/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do

        active=$(hyprctl activeworkspace -j | jq '.id')

        active_empty='true'
        let "i = $active"
        if [[ $(workspaces | jq --raw-output ".[] | select(.id == \"$i\") | .windows") == 0 ]]; then active_empty='false'; fi

        echo "{\"workspaces\": $(workspaces),\"active\": $active,\"active_empty\": $active_empty}" 
        eww update workspaces="{\"workspaces\": $(workspaces),\"active\": $active,\"active_empty\": $active_empty}"
    done
fi

if [[ $1 == 'window' ]]; then 
    window_title
    socat -u UNIX-CONNECT:/run/user/1000/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
        window_title
    done
fi
