#!/usr/bin/env bash

PRIMARY_DISPLAY='eDP-1'

open_desktop() {
    screen_id=$1
    echo "Opening on $screen_id"

    window="desktop"
    if [[ $screen_id == $PRIMARY_DISPLAY ]]; then
        window="desktop-clock"
    fi

    # Check if the window is already open on the screen
    open_state=$(eww active-windows | grep -w "$screen_id: $window")

    if [[ ! -z $open_state ]]; then
        echo "Already open"
        return
    fi

    # Open the specified window on the screen
    eww open --screen "$screen_id" --id "$screen_id" --arg screen=$screen_id $window
}

close_desktop() {
    screen_id=$1
    echo "Closing window on $screen_id"
    eww close "$screen_id"
}

handle_monitor() {
    ACTIVE=$(eww active-windows)
    MONITORS=$(swaymsg -t get_outputs | jq -r '.[].name')

    while IFS= read -r active; do
        IFS=': ' read -r active_id window_name <<< "$active"

        found=false
        while IFS= read -r screen_id; do
            [[ $screen_id == $active_id ]] && found=true
        done <<< "$MONITORS"

        if [[ $found == false ]]; then
            echo "$active_id has been removed"
            close_desktop "$active_id"
        fi
    done <<< "$ACTIVE"

    while IFS= read -r screen_id; do
        open_desktop "$screen_id"
    done <<< "$MONITORS"
}

window_title() {
    echo $(swaymsg -t get_tree | jq -r '.. | select(.type? == "con" and .focused == true).name')
}

get_workspaces() {
    swaymsg -t get_tree | jq '
        [
            .nodes[] as $output
            | $output.nodes[]
            | recurse(.nodes[] | objects)
            | select(.type == "workspace")
            | {
                id: .name |  tonumber? // .,
                screen: $output.name,
                windows: (
                [ .. | objects | select(.type == "con" and .name?) ] | length
                )
            }
        ]
        '
}

get_outputs() {
    swaymsg -t get_tree | jq '
        reduce .nodes[] as $output ({}; . + { ($output.name): { current_workspace: ($output.current_workspace | tonumber? // $output.current_workspace) } })
    '
}

get_outputs_workspaces() {
    workspaces=$(get_workspaces)
    outputs=$(get_outputs)

    jq -n --argjson outputs "$outputs" --argjson workspaces "$workspaces" '
        $outputs
        | to_entries
        | map(
            . as $e
            | $e.value.windows =
                if $e.value.current_workspace == null then
                    null
                else
                    ($workspaces[] | select(.id == $e.value.current_workspace) | .windows)
                end
            )
        | from_entries
        '
}

if [[ $1 == 'outputs' ]]; then
    # Initial output data
    eww update outputs="$(get_outputs_workspaces)"

    swaymsg -m -t subscribe '["workspace","window", "output"]' | while read -r line; do
        eww update outputs="$(get_outputs_workspaces)"
    done
fi

if [[ $1 == 'monitor' ]]; then
    # Initialize existing monitors
    handle_monitor

    swaymsg -m -t subscribe '["output"]' | while read -r line; do
        handle_monitor
    done
fi