gaps outer 2
gaps inner 5

default_border pixel 2
default_floating_border normal

set $color1     #1d1d1d
set $color2     #c3dde7ee
set $color3     #e78a4e
set $color4     #928374

# define colors for windows:
#class                          border          bground         text            indicator       child_border
client.focused               $color2           $color1         $color3           $color2         $color2
client.unfocused             $color4           $color1         $color4           $color2         $color1
client.focused_inactive      $color4           $color1         $color4           $color1         $color1
client.urgent                $color3           $color3         $color2           $color2         $color1

# ### Windows defaults
# default_border pixel 2
# gaps inner 4
# gaps outer 20

# client.focused #15439e #000000 #e0e0e0 #2e9ef4 #15439e
# client.focused_inactive #595959 #000000 #e0e0e0 #2e9ef4 #595959
# client.unfocused #595959 #000000 #e0e0e0 #2e9ef4 #595959