#!/usr/bin/env bash

NUMBER_OF_WORKSPACES=6

window_class() {
    echo `hyprctl activewindow -j | jq --raw-output .class`
}

window_title() {
    echo `hyprctl activewindow -j | jq --raw-output .title`
    # echo `hyprctl activewindow -j | jq --raw-output .title` | sed 's/\(.\{48\}\).*/\1.../'
    # echo 'some long string value' | sed 's/\(.\{15\}\).*/\1.../'
    # title=`hyprctl activewindow -j | jq --raw-output .title`
    # echo "${title:0:48}"
}

workspaces (){
    # WORKSPACE_WINDOWS=$(hyprctl workspaces -j | jq 'map({key: .id | tostring, value: .windows}) | from_entries')
    # seq 1 $NUMBER_OF_WORKSPACES | jq --argjson windows "${WORKSPACE_WINDOWS}" --slurp -Mc 'map(tostring) | map({id: ., windows: ($windows[.]//0)})'
    # hyprctl workspaces -j | jq 'map({key: .id | tostring, value: .windows}) | from_entries'
    # hyprctl workspaces -j | jq 'map({key: .id | tostring, value: .windows})'
    hyprctl workspaces -j | jq 'map({id: .id | tostring, windows: .windows})' | tr -d '\n'
}

if [[ $1 == 'workspaces' ]]; then 
    echo "{ \"workspaces\": $(workspaces), \"active\": 1, \"active_empty\": true }"
    socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
        active=$(eww get workspaces | jq .active)
        if [[ ${line:0:9} == 'workspace' ]]; then
            active=${line:11:2}
        fi

        active_empty='true'
        # let "i = $active - 1"
        let "i = $active"
        # if [[ $(workspaces | jq --raw-output .[$i].windows) -gt 0 ]]; then active_empty='false'; fi
        # if [[ $(workspaces | jq --raw-output .[$i].windows) == 0 ]]; then active_empty='false'; fi
        if [[ $(workspaces | jq --raw-output ".[] | select(.id == \"$i\") | .windows") == 0 ]]; then active_empty='false'; fi

        echo $i + $(workspaces | jq --raw-output ".[] | select(.id == \"$i\") | .windows") + "$active_empty"
        # echo $i + $(workspaces | jq --raw-output ".[] | select(.id == $i)") + "$active_empty"
        # echo $(workspaces | jq --raw-output ".[] | select(.id == \"$i\")")

        echo "{
            \"workspaces\": $(workspaces),
            \"active\": $active,
            \"active_empty\": $active_empty
        }" 
        eww update workspaces="{
            \"workspaces\": $(workspaces),
            \"active\": $active,
            \"active_empty\": $active_empty
        }" 

        eww update dock_reveal="$active_empty"
    done
fi

if [[ $1 == 'window' ]]; then 
    window_title
    socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
        window_title
    done
fi
