#!/usr/bin/env bash

#pkill eww || true
#pkill myshell || true
eww daemon
 
# HDMI=$(hyprctl monitors -j | jq .[1].name)
# if [[ $HDMI == '"HDMI-A-1"' ]]; then
#     # open both monitor stuff
# else
#     # open main monitror stuff
# fi

eww open bar
# eww open dock
eww open desktop
#eww open desktop1
eww open notifications_popup
# eww inspector

$HOME/.config/eww/scripts/myshell/./myshell --eww --file
